#!/bin/bash

# exit immediately if an error occurs
set -euo pipefail

# Quick helper to escape arguments when passing to ./gradlew cli:run

# Pass all args to be escaped for passing to gradle build
function escapeArgs() {
  # Iterate through arguments after the first one since gradle requires args via an explicit flag.
  escapedArguments=''
  for arg in "${@:1}"; do
    arg="${arg//\\/\\\\}"
    arg="\"${arg//\"/\\\"}\""

    # The arguments must be comma separated and passed via the --args flag to gradle.
    # -z checks for the empty, initial case to start building the string.
    if [ -z "$escapedArguments" ]; then
      escapedArguments="--args=$arg"
    else
      escapedArguments="$escapedArguments $arg"
    fi
  done

  echo "$escapedArguments"
}

currentDir=$(dirname -- "$0")
# Need to be in the root project directory for ./gradlew
cd "$currentDir/.."

escapedArguments="$(escapeArgs "$@")"
echo escapeArgs: "$escapedArguments"
./gradlew cli:run "$escapedArguments"
